/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hellomysql;
import java.util.List;

import hellomysql.controller.MainController;
import hellomysql.model.Persona;
import hellomysql.repositories.PersonaDAO;
import hellomysql.repositories.PersonaDaoImpl;
import hellomysql.view.MainView;

public class App {

    public static void main(String[] args) {
        MainController controller = new MainController();
        MainView mainView = new MainView(controller);
        mainView.view();
    }
}
